export const headers = [
  "ID",
  "Name",
  "Country",
  "City",
  "Language",
  "Job",
  "Company",
  "Income",
  "Currency",
  "Email",
  "Phone",
  "Product",
  "Date",
  "Score",
  "Amount"
];

export const filterHeader = [
  "id",
  "name",
  "country",
  "city",
  "language",
  "job",
  "company",
  "income",
  "currency",
  "email",
  "phone",
  "product",
  "date",
  "score",
  "amount"
]

export const data = [
  {
      "key_id": "1",
      "id": "1",
      "name": "Maria Garcia",
      "country": "Mexico",
      "city": "Mexico City",
      "language": "Spanish",
      "job": "Engineer",
      "company": "Acme Corp",
      "income": "5500000",
      "currency": "MXN",
      "email": "maria@example.com",
      "phone": "+1 555-1001",
      "product": "Hardware",
      "date": "2/2/2024",
      "score": "2",
      "amount": "110000"
  },
  {
      "key_id": "2",
      "id": "2",
      "name": "Akira Tanaka",
      "country": "Japan",
      "city": "Tokyo",
      "language": "Japanese",
      "job": "Analyst",
      "company": "XYZ Inc",
      "income": "6000000",
      "currency": "JPY",
      "email": "akira@example.com",
      "phone": "+1 555-1002",
      "product": "Services",
      "date": "3/3/2024",
      "score": "3",
      "amount": "120000"
  },
  {
      "key_id": "3",
      "id": "3",
      "name": "Wei Zhang",
      "country": "China",
      "city": "Beijing",
      "language": "Mandarin",
      "job": "Designer",
      "company": "ABC Ltd",
      "income": "6500000",
      "currency": "CNY",
      "email": "wei@example.com",
      "phone": "+1 555-1003",
      "product": "Support",
      "date": "4/4/2024",
      "score": "4",
      "amount": "130000"
  },
  {
      "key_id": "4",
      "id": "4",
      "name": "Priya Patel",
      "country": "India",
      "city": "Mumbai",
      "language": "Hindi",
      "job": "Consultant",
      "company": "Supreme Co",
      "income": "7000000",
      "currency": "INR",
      "email": "priya@example.com",
      "phone": "+1 555-1004",
      "product": "Training",
      "date": "5/5/2024",
      "score": "5",
      "amount": "140000"
  },
  {
      "key_id": "5",
      "id": "5",
      "name": "Hans Schmidt",
      "country": "Germany",
      "city": "Berlin",
      "language": "German",
      "job": "Manager",
      "company": "Global Tech",
      "income": "7500000",
      "currency": "EUR",
      "email": "hans@example.com",
      "phone": "+1 555-1005",
      "product": "Software",
      "date": "6/6/2024",
      "score": "6",
      "amount": "150000"
  },
  {
      "key_id": "6",
      "id": "6",
      "name": "Sophie Martin",
      "country": "France",
      "city": "Paris",
      "language": "French",
      "job": "Engineer",
      "company": "Acme Corp",
      "income": "8000000",
      "currency": "EUR",
      "email": "sophie@example.com",
      "phone": "+1 555-1006",
      "product": "Hardware",
      "date": "7/7/2024",
      "score": "7",
      "amount": "160000"
  },
  {
      "key_id": "7",
      "id": "7",
      "name": "Mohammed Al-Farsi",
      "country": "UAE",
      "city": "Dubai",
      "language": "Arabic",
      "job": "Analyst",
      "company": "XYZ Inc",
      "income": "8500000",
      "currency": "AED",
      "email": "mohammed@example.com",
      "phone": "+1 555-1007",
      "product": "Services",
      "date": "8/8/2024",
      "score": "8",
      "amount": "170000"
  },
  {
      "key_id": "8",
      "id": "8",
      "name": "Ana Silva",
      "country": "Brazil",
      "city": "São Paulo",
      "language": "Portuguese",
      "job": "Designer",
      "company": "ABC Ltd",
      "income": "9000000",
      "currency": "BRL",
      "email": "ana@example.com",
      "phone": "+1 555-1008",
      "product": "Support",
      "date": "9/9/2024",
      "score": "9",
      "amount": "180000"
  },
  {
      "key_id": "9",
      "id": "9",
      "name": "Olga Ivanova",
      "country": "Russia",
      "city": "Moscow",
      "language": "Russian",
      "job": "Consultant",
      "company": "Supreme Co",
      "income": "9500000",
      "currency": "RUB",
      "email": "olga@example.com",
      "phone": "+1 555-1009",
      "product": "Training",
      "date": "10/10/2024",
      "score": "10",
      "amount": "190000"
  },
  {
      "key_id": "10",
      "id": "10",
      "name": "John Smith",
      "country": "USA",
      "city": "New York",
      "language": "English",
      "job": "Manager",
      "company": "Global Tech",
      "income": "10000000",
      "currency": "USD",
      "email": "john@example.com",
      "phone": "+1 555-1010",
      "product": "Software",
      "date": "11/11/2024",
      "score": "1",
      "amount": "200000"
  },
  {
      "key_id": "11",
      "id": "11",
      "name": "Maria Garcia",
      "country": "Mexico",
      "city": "Mexico City",
      "language": "Spanish",
      "job": "Engineer",
      "company": "Acme Corp",
      "income": "10500000",
      "currency": "MXN",
      "email": "maria@example.com",
      "phone": "+1 555-1011",
      "product": "Hardware",
      "date": "12/12/2024",
      "score": "2",
      "amount": "210000"
  },
  {
      "key_id": "12",
      "id": "12",
      "name": "Akira Tanaka",
      "country": "Japan",
      "city": "Tokyo",
      "language": "Japanese",
      "job": "Analyst",
      "company": "XYZ Inc",
      "income": "11000000",
      "currency": "JPY",
      "email": "akira@example.com",
      "phone": "+1 555-1012",
      "product": "Services",
      "date": "1/13/2024",
      "score": "3",
      "amount": "220000"
  },
  {
      "key_id": "13",
      "id": "13",
      "name": "Wei Zhang",
      "country": "China",
      "city": "Beijing",
      "language": "Mandarin",
      "job": "Designer",
      "company": "ABC Ltd",
      "income": "11500000",
      "currency": "CNY",
      "email": "wei@example.com",
      "phone": "+1 555-1013",
      "product": "Support",
      "date": "2/14/2024",
      "score": "4",
      "amount": "230000"
  },
  {
      "key_id": "14",
      "id": "14",
      "name": "Priya Patel",
      "country": "India",
      "city": "Mumbai",
      "language": "Hindi",
      "job": "Consultant",
      "company": "Supreme Co",
      "income": "12000000",
      "currency": "INR",
      "email": "priya@example.com",
      "phone": "+1 555-1014",
      "product": "Training",
      "date": "3/15/2024",
      "score": "5",
      "amount": "240000"
  },
  {
      "key_id": "15",
      "id": "15",
      "name": "Hans Schmidt",
      "country": "Germany",
      "city": "Berlin",
      "language": "German",
      "job": "Manager",
      "company": "Global Tech",
      "income": "12500000",
      "currency": "EUR",
      "email": "hans@example.com",
      "phone": "+1 555-1015",
      "product": "Software",
      "date": "4/16/2024",
      "score": "6",
      "amount": "250000"
  },
  {
      "key_id": "16",
      "id": "16",
      "name": "Sophie Martin",
      "country": "France",
      "city": "Paris",
      "language": "French",
      "job": "Engineer",
      "company": "Acme Corp",
      "income": "13000000",
      "currency": "EUR",
      "email": "sophie@example.com",
      "phone": "+1 555-1016",
      "product": "Hardware",
      "date": "5/17/2024",
      "score": "7",
      "amount": "260000"
  },
  {
      "key_id": "17",
      "id": "17",
      "name": "Mohammed Al-Farsi",
      "country": "UAE",
      "city": "Dubai",
      "language": "Arabic",
      "job": "Analyst",
      "company": "XYZ Inc",
      "income": "13500000",
      "currency": "AED",
      "email": "mohammed@example.com",
      "phone": "+1 555-1017",
      "product": "Services",
      "date": "6/18/2024",
      "score": "8",
      "amount": "270000"
  },
  {
      "key_id": "18",
      "id": "18",
      "name": "Ana Silva",
      "country": "Brazil",
      "city": "São Paulo",
      "language": "Portuguese",
      "job": "Designer",
      "company": "ABC Ltd",
      "income": "14000000",
      "currency": "BRL",
      "email": "ana@example.com",
      "phone": "+1 555-1018",
      "product": "Support",
      "date": "7/19/2024",
      "score": "9",
      "amount": "280000"
  },
  {
      "key_id": "19",
      "id": "19",
      "name": "Olga Ivanova",
      "country": "Russia",
      "city": "Moscow",
      "language": "Russian",
      "job": "Consultant",
      "company": "Supreme Co",
      "income": "14500000",
      "currency": "RUB",
      "email": "olga@example.com",
      "phone": "+1 555-1019",
      "product": "Training",
      "date": "8/20/2024",
      "score": "10",
      "amount": "290000"
  },
  {
      "key_id": "20",
      "id": "20",
      "name": "John Smith",
      "country": "USA",
      "city": "New York",
      "language": "English",
      "job": "Manager",
      "company": "Global Tech",
      "income": "15000000",
      "currency": "USD",
      "email": "john@example.com",
      "phone": "+1 555-1020",
      "product": "Software",
      "date": "9/21/2024",
      "score": "1",
      "amount": "300000"
  }
]