export const settings = {
      "showInCard": [
        {
          "id": 1,
          "title": "Profile Picture"
        },
        {
          "id": 2,
          "title": "First Name"
        },
        {
          "id": 3,
          "title": "Job Title"
        },
        {
          "id": 4,
          "title": "Department"
        },
        {
          "id": 5,
          "title": "Email"
        },
        {
          "id": 6,
          "title": "Mobile"
        }
      ],
      "showInProfile": [
        {
          "id": 1,
          "title": "Employee Id"
        },
        {
          "id": 2,
          "title": "Certification"
        },
        {
          "id": 3,
          "title": "Email"
        },
        {
          "id": 4,
          "title": "Department"
        },
        {
          "id": 5,
          "title": "Education"
        },
        {
          "id": 6,
          "title": "Skills"
        },
        {
          "id": 7,
          "title": "Languages"
        },
        {
          "id": 8,
          "title": "Location"
        },
        {
          "id": 9,
          "title": "Address"
        },
        {
          "id": 10,
          "title": "Birthday"
        },
        {
          "id": 11,
          "title": "Start Date"
        },
        {
          "id": 12,
          "title": "Manager"
        },
        {
          "id": 13,
          "title": "Gender"
        }
      ],
    }

export const dummyData_People = [
    {
        "key_id": "1",
        "employee_id": "EMP10022",
        "first_name": "Rafael",
        "last_name": "Brown",
        "gender": "Male",
        "email": "rafael.brown@company.com",
        "profile_picture": "https://drive.google.com/file/d/1mMP0xDH8Hb7yM8I6p3V7lU_jDhIc4xpA/view?usp=sharing",
        "department": "Finance",
        "job_title": "Accountant",
        "location": "Tokyo",
        "manager": "John Johnson",
        "start_date": "2024-11-22",
        "mobile": "+1-444-460-6807",
        "address": "2929 Park St",
        "city": "Sydney",
        "birthday": "1986-12-16",
        "skills": "Project Management, Sales, Python, Leadership",
        "languages": "Arabic",
        "education": "Bachelor of Business",
        "certification": "CPA, PMP"
    },
    {
        "key_id": "2",
        "employee_id": "EMP10023",
        "first_name": "Lily",
        "last_name": "Smith",
        "gender": "Female",
        "email": "lily.smith@company.com",
        "profile_picture": "https://drive.google.com/file/d/1xKfLGs26tPXbdp14KGuUuzxBYRpDia2N/view?usp=sharing",
        "department": "Engineering",
        "job_title": "Engineering Manager",
        "location": "Paris",
        "manager": "Elizabeth Johnson",
        "start_date": "2021-08-08",
        "mobile": "+1-516-942-8488",
        "address": "2328 Main St",
        "city": "Tokyo",
        "birthday": "2001-07-10",
        "skills": "Communication, SQL, Sales, Data Analysis",
        "languages": "English",
        "education": "Master of Engineering",
        "certification": "CPA"
    },
    {
        "key_id": "3",
        "employee_id": "EMP10025",
        "first_name": "Robert",
        "last_name": "Smith",
        "gender": "Male",
        "email": "robert.smith@company.com",
        "profile_picture": "https://drive.google.com/file/d/1400MRzD_y4w96OXeSbCqJmMAqQrgIjxE/view?usp=drive_link",
        "department": "Sales",
        "job_title": "Account Executive",
        "location": "Berlin",
        "manager": "James Williams",
        "start_date": "2020-05-17",
        "mobile": "+1-546-800-8331",
        "address": "6709 Lake St",
        "city": "San Francisco",
        "birthday": "1992-03-23",
        "skills": "Leadership, SQL",
        "languages": "Japanese, German",
        "education": "PhD in Data Science",
        "certification": "CISSP"
    },
    {
        "key_id": "4",
        "employee_id": "EMP10026",
        "first_name": "Daniel ",
        "last_name": "Rodriguez",
        "gender": "Male",
        "email": "daniel.rodriguez@company.com",
        "profile_picture": "https://drive.google.com/file/d/1QyQmnKzgGgSCeDMRvITdBrusPLiLoBKh/view?usp=drive_link",
        "department": "Marketing",
        "job_title": "Marketing Specialist",
        "location": "Paris",
        "manager": "Michael Davis",
        "start_date": "2016-01-24",
        "mobile": "+1-176-836-6836",
        "address": "4747 Oak St",
        "city": "London",
        "birthday": "1972-08-30",
        "skills": "SQL, Python, Data Analysis, Communication",
        "languages": "Spanish, Arabic",
        "education": "Bachelor of Business",
        "certification": "CISSP"
    },
    {
        "key_id": "5",
        "employee_id": "EMP10027",
        "first_name": "Ethan",
        "last_name": "Garcia",
        "gender": "Male",
        "email": "ethan.garcia@company.com",
        "profile_picture": "https://drive.google.com/file/d/1vLJPBOTfK6xDxCtncOtlIwTnaWsaxgWn/view?usp=drive_link",
        "department": "Engineering",
        "job_title": "QA Engineer",
        "location": "Sydney",
        "manager": "Elizabeth Williams",
        "start_date": "2020-09-15",
        "mobile": "+1-246-909-6649",
        "address": "8083 Maple St",
        "city": "Sydney",
        "birthday": "1960-04-11",
        "skills": "Communication, Data Analysis",
        "languages": "Japanese",
        "education": "MBA",
        "certification": "AWS Certified"
    },
    {
        "key_id": "6",
        "employee_id": "EMP10030",
        "first_name": "James",
        "last_name": "Miller",
        "gender": "Male",
        "email": "james.miller@company.com",
        "profile_picture": "https://drive.google.com/file/d/1gVvao-ajfcgz75d29QR_Vk9I-DXM5rJ-/view?usp=drive_link",
        "department": "Sales",
        "job_title": "Sales Manager",
        "location": "San Francisco",
        "manager": "James Williams",
        "start_date": "2020-10-04",
        "mobile": "+1-241-509-4290",
        "address": "1490 Park St",
        "city": "Tokyo",
        "birthday": "1969-03-20",
        "skills": "Sales, SQL",
        "languages": "Hindi",
        "education": "PhD in Data Science",
        "certification": "CPA"
    },
    {
        "key_id": "7",
        "employee_id": "EMP10032",
        "first_name": "Sophia",
        "last_name": "Johnson",
        "gender": "Female",
        "email": "sophia.johnson@company.com",
        "profile_picture": "https://drive.google.com/file/d/1DTo9EZyX23qqkhf8AgQb7_fIZzwqJIDT/view?usp=drive_link",
        "department": "Engineering",
        "job_title": "Software Engineer",
        "location": "London",
        "manager": "Robert Brown",
        "start_date": "2021-02-14",
        "mobile": "+1-834-648-5205",
        "address": "9346 Oak St",
        "city": "Berlin",
        "birthday": "1964-05-26",
        "skills": "JavaScript, Python, Sales, Communication",
        "languages": "Hindi, Arabic",
        "education": "Bachelor of Computer Science",
        "certification": "CPA"
    },
    {
        "key_id": "8",
        "employee_id": "EMP10033",
        "first_name": "Yara",
        "last_name": "Garcia",
        "gender": "Female",
        "email": "Yara.garcia@company.com",
        "profile_picture": "https://drive.google.com/file/d/1vSjQqg4Xp4ga_xkS43EVhrVgA8_vUhrX/view?usp=drive_link",
        "department": "Marketing",
        "job_title": "Marketing Director",
        "location": "Toronto",
        "manager": "Linda Davis",
        "start_date": "2021-04-06",
        "mobile": "+1-955-943-2247",
        "address": "3948 Maple St",
        "city": "New York",
        "birthday": "1975-02-06",
        "skills": "Marketing, Sales",
        "languages": "English, Spanish",
        "education": "Bachelor of Business",
        "certification": "CISSP, CPA"
    },
    {
        "key_id": "9",
        "employee_id": "EMP10039",
        "first_name": "Noah",
        "last_name": "Martinez",
        "gender": "Male",
        "email": "noah.martinez@company.com",
        "profile_picture": "https://drive.google.com/file/d/1quXXT8UE3mmYHyKslsg5U5fm1bnaL2t7/view?usp=drive_link",
        "department": "Engineering",
        "job_title": "QA Engineer",
        "location": "London",
        "manager": "Robert Miller",
        "start_date": "2021-09-13",
        "mobile": "+1-731-865-9948",
        "address": "5411 Maple St",
        "city": "Berlin",
        "birthday": "1996-11-06",
        "skills": "Project Management, Python, Communication",
        "languages": "Spanish, Japanese",
        "education": "Master of Engineering",
        "certification": "CPA, CISSP"
    },
    {
        "key_id": "10",
        "employee_id": "EMP10043",
        "first_name": "Oliver",
        "last_name": "Jones",
        "gender": "Male",
        "email": "oliver.jones@company.com",
        "profile_picture": "https://drive.google.com/file/d/1JZy4nzgpgyYazaJ1_hGj5HNdh-7EwCPF/view?usp=drive_link",
        "department": "Finance",
        "job_title": "Finance Director",
        "location": "Toronto",
        "manager": "Linda Williams",
        "start_date": "2022-09-12",
        "mobile": "+1-292-331-3430",
        "address": "5229 Lake St",
        "city": "Sydney",
        "birthday": "1990-09-08",
        "skills": "Sales, Communication, Communication",
        "languages": "French, Mandarin",
        "education": "Bachelor of Computer Science",
        "certification": "CPA"
    },
    {
        "key_id": "11",
        "employee_id": "EMP10044",
        "first_name": "Charlotte",
        "last_name": "Smith",
        "gender": "Female",
        "email": "charlotte.smith@company.com",
        "profile_picture": "https://drive.google.com/file/d/1WkAZyFM9fM_Ii3rdUBvAG3vzUBwCUHRy/view?usp=drive_link",
        "department": "Sales",
        "job_title": "Sales Representative",
        "location": "Mumbai",
        "manager": "Robert Jones",
        "start_date": "2016-01-01",
        "mobile": "+1-787-993-6055",
        "address": "5057 Main St",
        "city": "Tokyo",
        "birthday": "1993-10-19",
        "skills": "JavaScript, Marketing",
        "languages": "French",
        "education": "Bachelor of Business",
        "certification": "CPA, AWS Certified"
    },
    {
        "key_id": "12",
        "employee_id": "EMP10045",
        "first_name": "John",
        "last_name": "Martinez",
        "gender": "Male",
        "email": "john.martinez@company.com",
        "profile_picture": "https://drive.google.com/file/d/16k8UdT7A1fBvRU1C41Ctl2DarWaQrnst/view?usp=drive_link",
        "department": "Engineering",
        "job_title": "Technical Lead",
        "location": "San Francisco",
        "manager": "Linda Jones",
        "start_date": "2022-01-13",
        "mobile": "+1-976-781-9449",
        "address": "2181 Park St",
        "city": "Sydney",
        "birthday": "1955-05-24",
        "skills": "Marketing, Python, Communication, SQL",
        "languages": "Arabic, Spanish",
        "education": "Bachelor of Business",
        "certification": "CISSP, PMP"
    },
    {
        "key_id": "13",
        "employee_id": "EMP10004",
        "first_name": "Leo",
        "last_name": "Williams",
        "gender": "Male",
        "email": "leo.williams@company.com",
        "profile_picture": "https://drive.google.com/file/d/1Yqx1nOAamKp-pH0XlHRgg0k9kTrsk5rM/view?usp=sharing",
        "department": "Sales",
        "job_title": "Sales Director",
        "location": "Sydney",
        "manager": "William Jones",
        "start_date": "2018-03-01",
        "mobile": "+1-627-867-9404",
        "address": "4962 Lake St",
        "city": "Mumbai",
        "birthday": "1967-08-13",
        "skills": "Sales, Data Analysis, Communication, Communication",
        "languages": "German, French",
        "education": "Bachelor of Computer Science",
        "certification": "Scrum Master, PMP"
    },
    {
        "key_id": "14",
        "employee_id": "EMP10007",
        "first_name": "Miya",
        "last_name": "Smith",
        "gender": "Female",
        "email": "miya.smith@company.com",
        "profile_picture": "https://drive.google.com/file/d/1k62Jz2gsA4HVeNUmWpBVx7ws8M6wl83G/view?usp=sharing",
        "department": "Finance",
        "job_title": "Finance Director",
        "location": "London",
        "manager": "Patricia Johnson",
        "start_date": "2023-03-07",
        "mobile": "+1-570-524-4051",
        "address": "2429 Oak St",
        "city": "Singapore",
        "birthday": "1986-03-16",
        "skills": "Leadership, Communication, Communication",
        "languages": "English, Arabic",
        "education": "MBA",
        "certification": "AWS Certified"
    },
    {
        "key_id": "15",
        "employee_id": "EMP10009",
        "first_name": "Rubi",
        "last_name": "Johnson",
        "gender": "Female",
        "email": "rubi.johnson@company.com",
        "profile_picture": "https://drive.google.com/file/d/1FxXLjgOyikX91COyWD7cCRPhGl3zGokG/view?usp=sharing",
        "department": "Marketing",
        "job_title": "Marketing Specialist",
        "location": "Sydney",
        "manager": "John Miller",
        "start_date": "2021-06-26",
        "mobile": "+1-481-677-6063",
        "address": "2188 Maple St",
        "city": "New York",
        "birthday": "1976-08-14",
        "skills": "Communication, Project Management, Python, JavaScript",
        "languages": "French",
        "education": "PhD in Data Science",
        "certification": "Scrum Master, CISSP"
    },
    {
        "key_id": "16",
        "employee_id": "EMP10015",
        "first_name": "James",
        "last_name": "Davis",
        "gender": "Male",
        "email": "james.davis@company.com",
        "profile_picture": "https://drive.google.com/file/d/1Qjul0BPF0afzRGVlZi1d3NuUX_sGYNy2/view?usp=sharing",
        "department": "Finance",
        "job_title": "Finance Manager",
        "location": "Paris",
        "manager": "Mary Miller",
        "start_date": "2023-06-08",
        "mobile": "+1-341-146-1861",
        "address": "8814 Main St",
        "city": "New York",
        "birthday": "1959-09-10",
        "skills": "Leadership, Python, SQL, Communication",
        "languages": "German",
        "education": "Bachelor of Computer Science",
        "certification": "CPA"
    },
    {
        "key_id": "17",
        "employee_id": "EMP10018",
        "first_name": "Mary",
        "last_name": "Martinez",
        "gender": "Female",
        "email": "mary.martinez@company.com",
        "profile_picture": "https://drive.google.com/file/d/1kEmCr8qzmgMBzlpskINBttQ76IxgHBUY/view?usp=sharing",
        "department": "Marketing",
        "job_title": "Digital Marketing Manager",
        "location": "London",
        "manager": "William Martinez",
        "start_date": "2022-08-04",
        "mobile": "+1-733-890-4888",
        "address": "3662 Main St",
        "city": "San Francisco",
        "birthday": "1970-12-10",
        "skills": "Project Management, Data Analysis, JavaScript, Communication",
        "languages": "English, Japanese",
        "education": "Bachelor of Computer Science",
        "certification": "PMP"
    },
    {
        "key_id": "18",
        "employee_id": "EMP10021",
        "first_name": "Michael",
        "last_name": "Smith",
        "gender": "Male",
        "email": "michael.smith@company.com",
        "profile_picture": "https://drive.google.com/file/d/1vgYxhDAjLxF0qLuwi4O126z6pNPt5Cew/view?usp=sharing",
        "department": "Engineering",
        "job_title": "Technical Lead",
        "location": "Sydney",
        "manager": "Michael Brown",
        "start_date": "2017-07-25",
        "mobile": "+1-940-523-8370",
        "address": "2459 Main St",
        "city": "Toronto",
        "birthday": "1970-03-20",
        "skills": "Python, SQL",
        "languages": "Hindi",
        "education": "MBA",
        "certification": "PMP"
    },
    {
        "key_id": "19",
        "employee_id": "EMP10048",
        "first_name": "William",
        "last_name": "Rodriguez",
        "gender": "Female",
        "email": "william.rodriguez@company.com",
        "profile_picture": "https://drive.google.com/file/d/1SxxwR7hjczaIYZATj7BfUYjIs1_Gqsbg/view?usp=drive_link",
        "department": "Finance",
        "job_title": "Finance Director",
        "location": "Singapore",
        "manager": "Elizabeth Miller",
        "start_date": "2018-09-14",
        "mobile": "+1-818-699-5850",
        "address": "7033 Lake St",
        "city": "London",
        "birthday": "1973-04-25",
        "skills": "Sales, Marketing, Communication",
        "languages": "Spanish",
        "education": "PhD in Data Science",
        "certification": "CISSP"
    },
    {
        "key_id": "20",
        "employee_id": "EMP10050",
        "first_name": "John",
        "last_name": "Rodriguez",
        "gender": "Male",
        "email": "john.rodriguez@company.com",
        "profile_picture": "https://drive.google.com/file/d/1FQBIt-5Y6BzHjBC5_uO-NCuTbI0fGTlp/view?usp=drive_link",
        "department": "HR",
        "job_title": "HR Coordinator",
        "location": "Singapore",
        "manager": "Elizabeth Brown",
        "start_date": "2020-11-30",
        "mobile": "+1-436-600-7798",
        "address": "5945 Oak St",
        "city": "Singapore",
        "birthday": "1986-05-10",
        "skills": "SQL, Project Management",
        "languages": "Mandarin, English",
        "education": "PhD in Data Science",
        "certification": "AWS Certified, PMP"
    },
    {
        "key_id": "21",
        "employee_id": "EMP10051",
        "first_name": "Soren",
        "last_name": "Jones",
        "gender": "Male",
        "email": "soren.jones@company.com",
        "profile_picture": "https://drive.google.com/file/d/1A_SROw9qbLlznLcn2qVxTTOiVHK5i1FV/view?usp=drive_link",
        "department": "Finance",
        "job_title": "Finance Director",
        "location": "Sydney",
        "manager": "Elizabeth Garcia",
        "start_date": "2022-07-11",
        "mobile": "+1-186-105-8841",
        "address": "1022 Oak St",
        "city": "Singapore",
        "birthday": "1958-12-08",
        "skills": "Project Management, SQL",
        "languages": "Mandarin, Spanish",
        "education": "MBA",
        "certification": "CISSP, AWS Certified"
    },
    {
        "key_id": "22",
        "employee_id": "EMP10052",
        "first_name": "Michael",
        "last_name": "Brown",
        "gender": "Male",
        "email": "michael.brown@company.com",
        "profile_picture": "https://drive.google.com/file/d/1YOwdQc7goaPttqRh98yPkdvCTkv5Pz7M/view?usp=drive_link",
        "department": "Marketing",
        "job_title": "Marketing Director",
        "location": "Mumbai",
        "manager": "Robert Miller",
        "start_date": "2022-02-24",
        "mobile": "+1-870-867-9101",
        "address": "1894 Park St",
        "city": "New York",
        "birthday": "2000-12-20",
        "skills": "Leadership, SQL",
        "languages": "Spanish",
        "education": "Bachelor of Business",
        "certification": "CPA"
    },
    {
        "key_id": "23",
        "employee_id": "EMP10053",
        "first_name": "John",
        "last_name": "Garcia",
        "gender": "Male",
        "email": "john.garcia@company.com",
        "profile_picture": "https://drive.google.com/file/d/1arSAGSb5PzEOSrueX7AzhYenPor7x0A4/view?usp=drive_link",
        "department": "Finance",
        "job_title": "Controller",
        "location": "Paris",
        "manager": "Linda Davis",
        "start_date": "2017-01-23",
        "mobile": "+1-558-932-8002",
        "address": "6747 Maple St",
        "city": "London",
        "birthday": "1996-11-23",
        "skills": "Marketing, JavaScript, Sales, Project Management",
        "languages": "Mandarin",
        "education": "PhD in Data Science",
        "certification": "CPA, Scrum Master"
    },
    {
        "key_id": "24",
        "employee_id": "EMP10054",
        "first_name": "Jennifer",
        "last_name": "Johnson",
        "gender": "Male",
        "email": "jennifer.johnson@company.com",
        "profile_picture": "https://drive.google.com/file/d/1yVALoklgfuneBHxDq8Y5avBUMEQ7TBvs/view?usp=drive_link",
        "department": "Finance",
        "job_title": "Finance Manager",
        "location": "San Francisco",
        "manager": "Michael Jones",
        "start_date": "2018-04-27",
        "mobile": "+1-424-437-7945",
        "address": "3745 Oak St",
        "city": "Mumbai",
        "birthday": "1955-04-30",
        "skills": "SQL, Data Analysis",
        "languages": "French",
        "education": "Bachelor of Business",
        "certification": "CISSP"
    },
    {
        "key_id": "25",
        "employee_id": "EMP10055",
        "first_name": "Linda",
        "last_name": "Brown",
        "gender": "Female",
        "email": "linda.brown@company.com",
        "profile_picture": "https://drive.google.com/file/d/1WkAZyFM9fM_Ii3rdUBvAG3vzUBwCUHRy/view?usp=drive_link",
        "department": "HR",
        "job_title": "HR Manager",
        "location": "Singapore",
        "manager": "James Davis",
        "start_date": "2020-07-17",
        "mobile": "+1-742-907-5977",
        "address": "517 Lake St",
        "city": "Berlin",
        "birthday": "1975-04-16",
        "skills": "Leadership, Python, Marketing",
        "languages": "Mandarin",
        "education": "PhD in Data Science",
        "certification": "CPA"
    },
    {
        "key_id": "26",
        "employee_id": "EMP10059",
        "first_name": "Robert",
        "last_name": "Brown",
        "gender": "Male",
        "email": "robert.brown@company.com",
        "profile_picture": "https://drive.google.com/file/d/1uKWBTUznWoVQ0kLHuEgMbYlzOw9I0tc9/view?usp=drive_link",
        "department": "Engineering",
        "job_title": "Technical Lead",
        "location": "Paris",
        "manager": "Jennifer Jones",
        "start_date": "2019-07-28",
        "mobile": "+1-954-673-2658",
        "address": "4526 Oak St",
        "city": "Sydney",
        "birthday": "1961-08-19",
        "skills": "Communication, Sales, Project Management, Python",
        "languages": "English, Mandarin",
        "education": "MBA",
        "certification": "AWS Certified"
    },
    {
        "key_id": "27",
        "employee_id": "EMP10060",
        "first_name": "Kai",
        "last_name": "Williams",
        "gender": "Male",
        "email": "kai.williams@company.com",
        "profile_picture": "https://drive.google.com/file/d/1gTn0dGH1sMbwMHg6-ZWElZkTWfGjP8Mr/view?usp=drive_link",
        "department": "Marketing",
        "job_title": "Content Writer",
        "location": "Paris",
        "manager": "Patricia Martinez",
        "start_date": "2019-01-20",
        "mobile": "+1-785-424-4453",
        "address": "9342 Lake St",
        "city": "Toronto",
        "birthday": "1979-11-29",
        "skills": "Project Management, SQL, JavaScript",
        "languages": "Hindi, Arabic",
        "education": "Master of Engineering",
        "certification": "PMP"
    }
]